### ISSUE TITLE
The mod crash server and this doesn't start

### ISSUE THREAD

**Issue by Autopoietico** [CleverNucleus/Entitled#1]
Hello, I was trying to use this mod for a modpack that I'm creating, to be specific the file Entitled.1.0.2-mc1.12.2.jar, but the mod crash only when use in a server.
I attach the crash report
[crash-2021-03-17_19.46.39-server.txt](https://github.com/CleverNucleus/Entitled/files/6159474/crash-2021-03-17_19.46.39-server.txt)

**Comment by CleverNucleus** [comment]
Hi there,
In line with the forge modding community, 1.12.2 is no longer supported. I recommend updating to the latest version (at time of writing: 1.2.3-1.16.4).

Thanks.

**Comment by Autopoietico** [comment]
Oh thanks for the answer, right now all the important mods are stuck in the 1.12.2, but I understand that you don't want to work in older versions.
